name: lofousu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_svg: ^2.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_app_check: ^0.4.1+2
  url_launcher: ^6.2.1
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icons/back.png
    - assets/icons/filter.png
    - assets/icons/whatsapp.png
    - assets/icons/phone.png
    - assets/icons/instagram.png
    - assets/icons/mail.png
    - assets/images/dompet1.png
    - assets/images/dompet2.png
    - assets/images/dompet3.png
    - assets/images/avatar.jpg
    - assets/images/default.png
    - assets/images/pp.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/app_icon.png"